<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.5
 * Time: 16:28
 */

namespace app\common\model;


use think\Model;

class Drivers extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $autoWriteTimestamp = true;
    protected $createTime = 'creattime';
    protected $updateTime = false;

    public function userFormat($userInfo)
    {
        $user = [];
        $user['driver_id'] = $userInfo['id'];
        $user['logo'] = $userInfo['logo'];
        $user['name'] = $userInfo['name'];
        $user['rel_name'] = $userInfo['rel_name'];
        $user['telephone'] = $userInfo['telephone'];
        $user['car'] = $userInfo['car'];
        $user['car_no'] = $userInfo['car_no'];
        return $user;
    }

    /**
     * 获取用户基本信息
     */
    public function getUserInfo($res)
    {
        return $this->userFormat($res);
    }

    /**
     * 根据手机号
     * @param $telephone
     * @return bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function checkIsExist($telephone)
    {
        $res = $this->where('phone', 'eq', $telephone)->find();
        if ($res) {
            return false;
        } else {
            return true;
        }
    }

}