<?php
/**
 * 用户实体类
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018\1\24 0024
 * Time: 17:01
 */

namespace app\common\model;


use think\Model;

class User extends Model
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    protected $autoWriteTimestamp = true;
    protected $createTime = 'creattime';
    protected $updateTime = false;

    public function userFormat($userInfo)
    {
        $user = [];
        $user['user_id'] = $userInfo['id'];
        $user['logo'] = $userInfo['logo'];
        $user['username'] = $userInfo['username'];
        $user['telephone'] = $userInfo['telephone'];
        return $user;
    }

    /**获取用户基本信息
     *
     */
    public function getUserInfo($res)
    {
        $data = [
            'id' => $res['id'],
            'username' => $res['name'],
            'logo' => $res['logo'],
            'remain_cost'=>$res['remain_cost'],
            'telephone'=>$res['telephone']
        ];
        return $this->userFormat($data);

    }

    /**
     * 根据手机号
     * @param $telephone
     * @return bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function checkIsExist($telephone)
    {
        $res = $this->where('phone', 'eq', $telephone)->find();
        if ($res) {
            return false;
        } else {
            return true;
        }
    }

}