<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/19
 * Time: 15:34
 */

namespace app\shop\controller;


use think\Controller;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(request()->controller() != 'Index'){
            $this->assign('breadNav', $this->getBreadNav());
        }
//        if(!self::checkIsLogin()){
//            $this->redirect('Pub/login');
//        }
    }

    public function checkIsLogin()
    {
        if (session(config('shopkey'))) {
            if (!defined(config('shopkey'))) {
                define('SHOP_ID', session(config('shopkey')));
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * 获取面包屑导航
     */
    private function getBreadNav()
    {
        require_once APP_PATH . 'shop/leftmenu.php';
        $menuArr = $leftmenu;
        $action = request()->controller();
        $method = request()->action();
        $bread = "";
        foreach ($menuArr as $m) {
            foreach ($m['navChild'] as $t){
                if($t['url'] == $action.'/'.$method){
                    $bread = '<i class="Hui-iconfont">&#xe67f;</i> ' . $m['navName'] . ' <span class="c-gray en">&gt;</span> ' . $t["navName"] ;
                    break;
                }
            }
        }
        return $bread;
    }
}