<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018.5.5
 * Time: 17:18
 */

namespace app\shop\controller;



class Drivers extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 司机列表
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function index()
    {
        $drivers = model('drivers')->select();
        $this->assign('drivers', $drivers);
        $status = [
            '0' => '未申请',
            '1' => '申请未审核',
            '2' => '审核通过',
            '3' => '审核拒绝'
        ];
        $this->assign('status', $status);
        return $this->fetch();
    }

    /**
     * 司机列表
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function verify()
    {
        $drivers = model('drivers')->where('status', 1)->select();
        $this->assign('drivers', $drivers);
        $status = [
            '0' => '未申请',
            '1' => '申请未审核',
            '2' => '审核通过',
            '3' => '审核拒绝'
        ];
        $this->assign('status', $status);
        return $this->fetch();
    }

    /**
     * 审核通过
     */
    public function sure()
    {
        $id = input('post.id');
        $res = model('drivers')->save([
            'status'=>2
        ], ['id'=>$id]);
        if($res){
            exit_json();
        }else{
            exit_json(-1, '处理失败');
        }

    }

    /**
     * 拒绝
     */
    public function refuse()
    {
        $id = input('post.id');
        $reason = input('post.reason');
        $res = model('drivers')->save([
            'status'=>3,
            'reason'=>$reason
        ], ['id'=>$id]);
        if($res){
            exit_json();
        }else{
            exit_json(-1, '处理失败');
        }
    }

    /**
     * 删除用户信息
     */
    public function delData()
    {
        $res = model('drivers')->where('id', input('post.id'))->delete();
        if($res){
            exit_json();
        }else{
            exit_json(-1, '删除失败');
        }
    }

    /**
     * 获取验证信息
     */
    public function getVinInfo()
    {
        $driver_id = input('driver_id');
        $driver = model('drivers')->where('id', $driver_id)->find();
        $re = file_get_contents('http://v.juhe.cn/jszhc/query.php?name='.$driver['rel_name'].'&cardNo='.$driver['card_no'].'&carModels='.$driver['carModels'].'&firstGetDocDate='.$driver['firstGetDocDate'].'&archviesNo='.$driver['archviesNo'].'&key=aa1bca90c6f95bdf75218f1de33161cd');
        $res = json_decode($re, true);
        $this->assign('result', $res['result']);
        return $this->fetch();
    }

}