<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/19
 * Time: 14:22
 */

namespace app\shop\controller;


class Index extends Base
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function index()
    {
        require_once APP_PATH.'shop/leftmenu.php';
        $this->assign('leftmenu', $leftmenu);
        return $this->fetch();

    }

    public function baseIndex()
    {
        $data = [];
        $data['driver_num'] = model('drivers')->count();
        $data['user_num'] = model('user')->count();
        $data['order_num'] = db('order')->count();
        $this->assign('data', $data);
        return $this->fetch();
    }



}