<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/23
 * Time: 13:44
 */

namespace app\app\controller;


use think\Controller;

class BaseUser extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!self::checkUser(input('userid'))) {
            exit_json(-1, '用户不存在');
        }
    }

    /**
     * 检验用户是否存在/已登录
     * @param $userid
     * @return bool
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function checkUser($userid)
    {
        if (!$userid) {
            return false;
        }
        $userModel = new \app\common\model\User();
        $res = $userModel->where('id', 'eq', $userid)->find();
        if ($res) {
            if (!defined('USER_ID')) {
                define('USER_ID', $userid);
            }
            return true;
        } else {
            return false;
        }
    }

}